use Mix.Config

# Configure your database
config :bebemayotte, Bebemayotte.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "odoo",
  password: "Mgbi@261!",
  #username: "postgres",
  #password: "postgres",
  database: "bebemayotte_dev",
  hostname: "localhost",
  port: 5432,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :bebemayotte, Bebemayotte.EBPRepo,
  adapter: Ecto.Adapters.Tds,
  username: "sa",
  password: "@ebp78EBP",
  database: "BB_MAY_0895452f-b7c1-4c00-a316-c6a6d0ea4bf4",
  hostname: "NS3072398",
  instance: "EBP_2019",
  port: 53735,
  odbc_driver: "{SQL Server Native Client 11.0}",
  pool_size: 10

# Configure mail
config :Bebemayotte, Bebemayotte.Mailer,
  adapter: Bamboo.SendGridAdapter,
  api_key: System.get_env("SENDGRID_API_KEY")

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :bebemayotte, BebemayotteWeb.Endpoint,
  http: [port: 4001],
  # https: [
  #   port: 4001,
  #   cipher_suite: :strong,
  #   certfile: "priv/cert/selfsigned.pem",
  #   keyfile: "priv/cert/selfsigned_key.pem"
  # ],
  url: [host: "localhost", port: 4001],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ],
  live_view: [
    signing_salt: "XUKQkfgb/a6YBHB5QqHwettiPnz/A7JX"
  ],
  # force_ssl: [hsts: false, rewrite_on: [:x_forwarded_proto], exlude: [], host: "localhost:4001"]
]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :bebemayotte, BebemayotteWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/bebemayotte_web/(live|views)/.*(ex)$",
      ~r"lib/bebemayotte_web/templates/.*(eex)$",
      ~r{lib/bebemayotte_web/live/.*(ex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
